name: Cargo Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write     # Required for OIDC token exchange

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install LLVM toolchain (clang)
        uses: KyleMayes/install-llvm-action@v2.0.9
        with:
          version: "19"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.95.0
          components: rustfmt, clippy
          targets: riscv64imac-unknown-none-elf
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - run: |
          cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
